config/routes.rb
Photos::Application.routes.draw do
  resources :albums

  resources :photos do
    member do
      get 'tags'
      get 'people'
    end
  end
  
  resources :tags do
    member do
      get 'photos'
    end
  end

  resources :people do
    member do
      get 'photos'
    end
  end
  
  get "home/index"
  get "home/new"
  get "static_pages/about"
  
  match 'photo/people' => 'photos#photo_people'
  match 'person/photos' => 'people#person_photos'
  match 'people_by_photo_count' => 'people#photo_by_count'
  match 'people_by_name' => 'people#photo_by_name'
  match 'album/photos' => 'albums#album_photos'
  match 'album/thumbnails' => 'albums#album_thumbnails'
  match 'album/recent' => 'albums#album_recent'
  

  root :to => 'home#index'

  

end

app/models/person.rb
class Person < ActiveRecord::Base
    attr_accessible :name, :url, :urlheight, :urlwidth
    
    validates :name, :presence => true
   
    has_many :facelocations
    has_many :photos, :through => :facelocations
    
    def self.search(search)
      if search
        where('name LIKE ?', "%#{search}%")
      else
        all
      end
    end
    
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  # include helper methods from application_helper.rb
  helper ApplicationHelper

  # GET /people
  # GET /people.json
  def index
    # for simple search
    # @people= Person.search(params[:search])
    
    if (params[:q])
      @people= Person.search(params[:q])
    else
      @people= Person.order("name ASC")
    end
        
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/photos
  # GET /people/1.json/photos
  def photos
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person.photos }
    end
  end
  
  def person_photos
    person= Person.find(params[:id])
    piclist= person.photos.order('time DESC')
    set_cur_piclist(piclist, 0)
    
    if person
      respond_to do |format|
        format.json {render :json => piclist }
      end
    end
  end

  def photo_by_count
    people= Person.all
    
    a= Array.new(people.count, Hash.new)
    i= 0;
    people.each do |person|
      a[i]= {:count => person.photos.count, :person => person}
      i+= 1
    end
    a.sort_by!{ |h| h[:count]}.reverse!
    
    respond_to do |format|
      format.json {render json: a}
    end
  end
  
  def photo_by_name
    people= Person.order("name ASC")
    
    a= Array.new(people.count, Hash.new)
    i= 0;
    people.each do |person|
      a[i]= {:count => person.photos.count, :person => person}
      i+= 1
    end
    
    respond_to do |format|
      format.json {render json: a}
    end
  end

=begin
  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
=end
  
end

app/helpers/people_helper.rb
module PeopleHelper
  
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
  	<%= f.label :name %><br>
  	<%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag    "people", media:"all" %>
<%= javascript_include_tag "people" %>
<% end %>

<%= render "layouts/header" %>
<div class="this-page" data-type="all people">
  <div class= "sort-btn-group-wrap">
    <div class="sort-btn-group">
      <a class="btn" id="alpha"><i class="icon-arrow-down"></i> A..Z</a>
      <a class="btn" id="count"><i class="icon-arrow-down"></i> 1..9</a>
    </div>
  </div>
  <div id="rowholder">
    <div class="picrow"></div>
  </div>
</div>

<%= render "layouts/footer-large" %>


app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/photos.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag    "application", media:"all" %> 
  <%= stylesheet_link_tag    "people", media:"all" %>
  <%= javascript_include_tag "people"%>
<% end %>

<%= render "layouts/header" %>

<div class="this-page" data-type="person" data-id=<%= @person.id %> >
  <div id="rowholder">
    <div class="picrow"></div>
  </div>
</div>

<%
=begin %>
<div id="galleria" data-name="<%= @person.name %>" >
</div>

<div class="galleria-footer">
  <strong><%= @person.name %></strong><br>
</div>

<%
=end %>

<%= render "layouts/footer" %>


app/views/people/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>