config/routes.rb
Photos::Application.routes.draw do
  resources :albums

  resources :photos do
    member do
      get 'tags'
      get 'people'
    end
  end
  
  resources :tags do
    member do
      get 'photos'
    end
  end

  resources :people do
    member do
      get 'photos'
    end
  end
  
  get "home/index"
  get "home/new"
  get "static_pages/about"
  
  match 'photo/people' => 'photos#photo_people'
  match 'person/photos' => 'people#person_photos'
  match 'people_by_photo_count' => 'people#photo_by_count'
  match 'people_by_name' => 'people#photo_by_name'
  match 'album/photos' => 'albums#album_photos'
  match 'album/thumbnails' => 'albums#album_thumbnails'
  match 'album/recent' => 'albums#album_recent'
  

  root :to => 'home#index'

  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  
  # include ActsAsAdjacent
  
  attr_accessible :name, :width, :height, :orientation, :onlineid,
                  :focallength, :fstop, :iso, :exposure, :flash, :make, :model,
                  :thumburl, :url, :largeurl, :time
  
  validates :name, :presence => true
  validates :onlineid, :presence => true
  validates :thumburl, :presence => true
  validates :url, :presence => true
  validates :largeurl, :presence => true
  
  has_and_belongs_to_many :tags, :join_table => 'photo_tags'
  has_many :facelocations
  has_many :people, :through => :facelocations
  belongs_to :album

  def names_sorted_string
    names= ""
    self.people.each do |person|
      if names==""
        names= person.name
      else 
        names += ", " + person.name
      end
    end
    return names
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo= Photo.find(params[:id])
    id= params[:id].to_i
    @piclist= get_cur_piclist
    index= @piclist.index {
      |x| x.id==id
    }
    if (index>0)
      @prev= index-1
    else
      @prev= @piclist.length-1
    end
    if (index<(@piclist.length-1))
      @next= index+1
    else
      @next= 0
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end
  
  # GET /photos/1/tags
  # GET /photos/1.json/tags
  def tags
    @photo= Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end
  
  # GET /photos/1/people
  # GET /photos/1.json/people
  def people
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end
  
  # GET /photo/people.json
  def photo_people
    p= params[:q].split(":")
    album= Album.find(p[0])
    photo= album.photos.find(p[1])
    
    respond_to do |format|
      format.json {render :json => {:width => photo.width, :height => photo.height, :orientation => photo.orientation, :people => photo.people, :faces => photo.facelocations}}
    end
  end
  
=begin
  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
=end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
  	<%= f.label :path %><br />
  	<%= f.text_field :path %>
  </div>
  <div class= "field">
  	<%= f.label :width %><br />
  	<%= f.number_field :width %>
  </div>
  <div class= "field">
  	<%= f.label :height %><br />
  	<%= f.number_field :height %>
  </div>
  <div class= "field">
  	<%= f.label :date %><br />
  	<%= f.text_field :date %>
  </div>	
	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag    "photos", media:"all" %>
<%= javascript_include_tag "photos"%>
<% end %>

<div id="galleria">
  <% @photos.each do |photo| %>
    <% dir= Pathname(photo.path).dirname.to_s %>
    <% largename= Pathname(photo.path).basename.to_s %>
    <% smallname= "s_" + largename %>
    <% thumbname= "tn_" + largename %>
    <% largepath= "assets/" + dir + "/" + largename %>
    <% smallpath= dir + "/" + smallname %>
    <% thumbpath= dir + "/" + thumbname %>
    <% names= "Names: " %> 
    <% photo.people.order('name ASC').each do |person| %>
      <% fl= photo.facelocations.where("person_id = ?", person.id).first %>
      <% if (names != "Names: ") %>
        <% names += ", " %>
      <% end %>
      <% names += link_to person.name, photos_person_path(person), class: "pname", :'data-xloc' => fl.xloc, :'data-yloc' => fl.yloc, 
          :'data-width' => fl.width, :'data-height' => fl.height %> 
    <% end %>

    <%= link_to(largepath) do %>
      <%= image_tag(thumbpath, :'data-description' => names) %>
    <% end %>
  <% end %> 
</div>

<% 
=begin %>

<div class="oGallery-container">
  <ul id="oGallery">
    <% @photos.each do |photo| %>
      <% dir= Pathname(photo.path).dirname.to_s %>
      <% largename= Pathname(photo.path).basename.to_s %>
      <% smallname= "s_" + largename %>
      <% thumbname= "tn_" + largename %>
      <% largepath= dir + "/" + largename %>
      <% smallpath= dir + "/" + smallname %>
      <% thumbpath= "assets/" + dir + "/" + thumbname %>
      <% names= "Names: " %>
      <% photo.people.order('name ASC').each do |person| %>
        <% fl= photo.facelocations.where("person_id = ?", person.id).first %>
        <% if (names != "Names: ") %>
        <% names += ", " %>
      <% end %>
      <% names += link_to person.name, photos_person_path(person), class: "pname", :'data-xloc' => fl.xloc, :'data-yloc' => fl.yloc,
        :'data-width' => fl.width, :'data-height' => fl.height %>
    <% end %>
    <li>
      <%= image_tag(largepath, :'data-frame' => thumbpath) %>
      <!-- <%= link_to(largepath) do %> -->
      <!-- <%= image_tag(thumbpath, :'data-description' => names) %> -->
      <!-- <% end %> -->
    </li>
    <% end %>
  </ul>
</div>

<% 
=end %>


  <%= render "layouts/footer" %>

  <div id="facebox"></div>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/people.html.erb
<h1>Photo People</h1>

<h2> Photo Name: '<%= @photo.name %>' </h2>

<% @photo.people.each do |person| %>
	<%= person.name %><\br>
<% end %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag    "photos", media:"all" %>
<%= javascript_include_tag "photos" %>
<% end %>

<%= render "layouts/header" %>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span10">
      <div class="pull-left">
        <%= image_tag @photo.url, :class => "picture" %>
      </div>
    </div>
    <div class="span2">
      <div class= "prevnext">
        <%= link_to(image_tag(@piclist[@prev].thumburl), '/photos/'+@piclist[@prev].id.to_s) %>
      </div>
      <div class= "prevnext">
        <%= link_to(image_tag(@piclist[@next].thumburl), '/photos/'+@piclist[@next].id.to_s) %>
      </div>
      </br>      
      <div class= "picture-info">
        <strong>Picture</strong></br>
        Album: <%= link_to @photo.album.name, album_path(@photo.album) %></br>
        <%= 'Date: ' + (@photo.time ? @photo.time.strftime("%B %-d, %Y") : '?') %></br>        
        <%= 'Name: ' + @photo.name %></br>
      </div>
      </br>
      <div class= "picture-info">
        <strong>People</strong></br>
        <% people= @photo.people.order('name ASC') %>
        <% people.each do |person| %>
          <%= link_to person.name, photos_person_path(person) %></br>
        <% end %>
      </div>
      </br>
      <div class= "picture-info">
        <strong>Camera</strong></br>
        <%= 'Focal Length:' + @photo.focallength + ' mm f/' + @photo.fstop %></br>
        <%= 'Exposure: ' + @photo.exposure + 's' %></br>
        <%= 'ISO: ' + @photo.iso %></br>
        <%= 'Flash: ' + @photo.flash %></br>
        <%= 'Camera make: ' + @photo.make %></br>
        <%= 'Camera model: ' + @photo.model %></br>
      </div>
    </div>
  </div>
</div>

<%= render "layouts/footer" %>

app/views/photos/tags.html.erb
<h1>Photo Tags</h1>

<h2> Photo Name: '<%= @photo.name %>' </h2>

<% @photo.tags.each do |tag| %>
	<%= tag.name %><\br>
<% end %>

<%= link_to 'Back', photos_path %>