config/routes.rb
Photos::Application.routes.draw do
  resources :albums

  resources :photos do
    member do
      get 'tags'
      get 'people'
    end
  end
  
  resources :tags do
    member do
      get 'photos'
    end
  end

  resources :people do
    member do
      get 'photos'
    end
  end
  
  get "home/index"
  get "home/new"
  get "static_pages/about"
  
  match 'photo/people' => 'photos#photo_people'
  match 'person/photos' => 'people#person_photos'
  match 'people_by_photo_count' => 'people#photo_by_count'
  match 'people_by_name' => 'people#photo_by_name'
  match 'album/photos' => 'albums#album_photos'
  match 'album/thumbnails' => 'albums#album_thumbnails'
  match 'album/recent' => 'albums#album_recent'
  

  root :to => 'home#index'

  

end

app/views/layouts/_footer-large.html.erb
<div class= "footer-container">
  <!-- FOOTER -->
  <footer>
    <p class="pull-right">
      <a href="#">Back to top</a>
    </p>
    <p>
      &copy; 2013 Omid Sojoodi
    </p>
  </footer>
</div>

app/views/layouts/_footer.html.erb
<div class= "footer-container">
  <!-- FOOTER -->
  <footer>
    <p>
      &copy; 2013 Omid Sojoodi
    </p>
  </footer>
</div>


app/views/layouts/_header.html.erb
<div class= "header-container">
  <div class= "pull-right">
    <div class= "site-stats">
      <div class= "field">
        <div class= "data"><%= @stats['photos'].to_s %></div></br>Photos
        </div>
      <div class= "field">
        <div class= "data"><%= @stats['albums'].to_s %></div></br>Albums
      </div>
      <div class= "field">
        <div class= "data"><%= @stats['updated'].to_s %></div></br>Last update
      </div>
    </div>
  </div>  
  <!-- NAVBAR
  ================================================== -->
  <div class="navbar-wrapper">
    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- ><a class="brand" href="#">o! Photos</a> -->
        <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li class="active">
              <%= link_to("Home", home_index_path) %>
            </li>
            <li class="divider-vertical"></li>
            <li>
              <%= link_to("New", home_new_path) %>
            </li>
            <li class="divider-vertical"></li>
            <li>
              <%= link_to("Albums", albums_path) %>
            </li>
            <li class="divider-vertical"></li>
            <li>
              <%= link_to("People", people_path) %>
            </li>
            <li class="divider-vertical"></li>
            <li>
              <%= link_to("About", static_pages_about_path) %>
            </li>
            <li class="divider-vertical"></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!-- /.navbar-inner -->
    </div><!-- /.navbar -->
  </div><!-- /.navbar-wrapper -->
  <div class= "pull-left">
    <%= link_to image_tag("logo-small-1.png", :class => "logo"), home_index_path, class:"brand" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Omid's Photos</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Photos">
    <meta name="author" content="Omid Sojoodi">

    <!-- Le styles -->
    <%= stylesheet_link_tag "bootstrap/bootstrap.css" %>
    <%= stylesheet_link_tag "bootstrap/bootstrap-responsive.css" %>
    <%= stylesheet_link_tag "application", media:"all" %>
    <%= javascript_include_tag "application" %>
    <%= yield :head %>    

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="/assets/bootstrap/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="bootstrap/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="bootstrap/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="bootstrap/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="bootstrap/apple-touch-icon-57-precomposed.png">
    <!-- <link rel="shortcut icon" href="bootstrap/favicon.png"> -->
    
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="page-container">
    <%= yield %>
  </div>
  
  </body>
</html>